FROM centos:7
RUN ["/bin/sh", "-c", "yum -y update"]
RUN ["/bin/sh", "-c", "yum -y install sudo"]
RUN ["/bin/sh", "-c", "yum -y install python3"]
RUN ["/bin/sh", "-c", "pip3 install django"]
RUN ["/bin/sh", "-c", "yum -y install gcc"]

